spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890abcd
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 2592000000
